### ISSUE TITLE
[build] - How to build cjs and esm modules using project references ?

### ISSUE THREAD

**Issue by rkovalyov** [wixplosives/sample-monorepo#215]

**Comment by AviVahl** [comment]
Create two tsconfigs

**Comment by rkovalyov** [comment]
@AviVahl different tsconfig is solution )  but how to manage `references` , each packages set own `outDir` and extends `tsconfig.base.json`

**Comment by AviVahl** [comment]
Not ideal. The entire approach is to have a **single command** building the repository. it builds the tsconfig.json in the root which references all tsconfigs you care about.

**Comment by AviVahl** [comment]
Lets say I want to make the `"components"` library (here in this repository) build into `cjs` and `esm` folders.
- change `src/tsconfig.json` to build into `cjs`.
 -add `src/tsconfig.esm.json` which references `./tsconfig.json` next to it (depends on it and all its refs to be built), extends `tsconfig.base.json`, has `outDir` set to `esm`, and `module` as `esnext`.
- change the `package.json` of `"components"` to adjust for the new output folders, and add the `"module"` field.
- then there are several options... For example, I can reference the new `tsconfig.esm.json` from the root `tsconfig.json`, or I can create a separate `tsconfig.build.json` in the root referencing the root `tsconfig.json`.

**Comment by rkovalyov** [comment]
@AviVahl  thanks ) I did not notice your comment  and created structure like:

`tsconfig.base.json` - base options
`tsconfig.base.cjs.json` - extend base options and set `module`: `commonjs`
`tsconfig.base.esm.json`- extend base options and set `module`: `esnext`
`tsconfig.cjs.json` - references to `cjs` config file which extends `tsconfig.base.cjs.json` 
  ------ (ex. `{ "path": "./packages/components/src/tsconfig.cjs.json" }`)
`tsconfig.esm.json` - references to `esm` config file which extends `tsconfig.base.esm.json` 
  ------(ex `{ "path": "./packages/components/src/tsconfig.esm.json" }`,)
