### ISSUE TITLE
CI/CD and a Dockerfile

### ISSUE THREAD

**Issue by dasdachs** [wixplosives/sample-monorepo#406]
Thanks for the example monorepo! It is hard to find good examples. Would it be possible to provide a `Dockerfile`, and, if possible, an example CI/CD pipeline (Github actions, Jenkinsfile, etc.).

**Comment by AviVahl** [comment]
Happy to assist. :+1: 

I prefer to not put a `Dockerfile` here. Any base I might pick for the `Dockerfile` will be too opinionated and wouldn't cover many  possible use cases for this setup.

 I can imagine the [official node:16](https://hub.docker.com/_/node) docker image would be suffice for the shown example, as it's really contrived. We have repositories doing browser tests and extending the [playwright](https://hub.docker.com/_/microsoft-playwright) `Dockerfile` to execute tests while using a similar setup.

CI is shown in the form of GitHub Actions testing all commits. CD is not. My team has several types of development/deployment flows for different projects. _Most_ npm-based projects use manually-triggered versioning with automated CI publishing. [stylable](https://github.com/wix/stylable), for example, uses a setup based on this one together with [pleb](https://github.com/wixplosives/pleb) for automated publishing of new versions bumped in `master`. So does [file-services](https://github.com/wixplosives/file-services).

I can imagine stricter CD flows could be used for npm packages as long as one addresses some of the questions that come up regarding package versions, npm dist-tags, git tags, and interoperability with semver.
