### ISSUE TITLE
npmjs resolution of relative links in packages/*/README.md

### ISSUE THREAD

**Issue by ericprud** [wixplosives/sample-monorepo#487]
Typical of monorepos, this sample has npm packages in a `packages` directory, e.g. `@sample/app` is in `packages/app/`. From what I've seen in [my own monorepo](https://www.npmjs.com/package/@ts-jison/parser-generator), relative markdown links (backed by github repos) point to:

    https://github.com/\<group\>/\<repo\>/blob/HEAD/\<markdown-link\>

instead of

    https://github.com/\<group\>/\<repo\>/blob/HEAD/packages/\<package-dir\>/\<markdown-link\>

If you know how to make a relative link in `packages/app/` point to

    https://github.com/wixplosives/sample-monorepo/blob/HEAD/packages/app/\<markdown-link\>

, could you add an example to app's README?

**Comment by ericprud** [comment]
[nearby SO](https://stackoverflow.com/questions/62575382/relative-link-from-readme-md-to-another-file-in-package-rendered-in-npmjs) provides relative link clues that may help

**Comment by AviVahl** [comment]
I actually used to link using absolute URLs and that always worked: https://github.com/wixplosives/file-services/blob/master/README.md
(saw you did the same in your repo)

I've added relative links to the root README at https://github.com/wixplosives/sample-monorepo/commit/14e650ad04b25443bcb34f049bae9276e849eb76 and they appear to work in GitHub. This is much preferred, I think, as it will retain correctness in other branches as well (without always pointing to `main`).

It boils down to what's rendering the markdown to html, and whether it's aware of the base URL for that context.

Please let me know if that answers your question.

**Comment by ericprud** [comment]
> I actually used to link using absolute URLs and that always worked: https://github.com/wixplosives/file-services/blob/master/README.md (saw you did the same in your repo)

Yes, but it made me feel dirty.

> I've added relative links to the root README at [14e650a](https://github.com/wixplosives/sample-monorepo/commit/14e650ad04b25443bcb34f049bae9276e849eb76) and they appear to work in GitHub. This is much preferred, I think, as it will retain correctness in other branches as well (without always pointing to `main`).

nice. Tx!
