### ISSUE TITLE
Cannot find module '@sample/components' or its corresponding type declarations

### ISSUE THREAD

**Issue by SlahserZ** [wixplosives/sample-monorepo#546]
Hi, I like this sample but alert this error `Cannot find module '@sample/components' or its corresponding type declarations` after `pnpm run build`.

could you help me?

**Comment by AviVahl** [comment]
This repo uses npm@8. Specifically, the "resolutions" field and for running scripts.

You might be able to adapt it to pnpm, but that it outside the scope of what I'd like to support.

**Comment by SlahserZ** [comment]
Thanks a lot!
