### ISSUE TITLE
alt discussion

### ISSUE THREAD

**Issue by jeremy-coleman** [wixplosives/sample-monorepo#6]
Avi, sorry for the delay on updating the pull request.

Will you have a look at https://github.com/jeremy-coleman/monorepo-starterkit?

it's definitely not production worthy, but i'd like your feedback on the setup . there are also some useful scripts for auto-generating a typescript build config inside the scripts folder, but I just can't come up with a way to make it work practically with aliases. If you think it's all trash thats fine too, lol

**Comment by AviVahl** [comment]
apologies for the delayed response. am busy with tons of projects (both personal and work ones)...
several notes about the `monorepo-starterkit`:
- very cool. some nice tooling/configuration is used there.
- keep deps up to date! :P connect it to dependebot or similar service, or update manually.
- not sure why your need both `rollup` and `webpack` in the same repo. They provide the same functionality as far as I'm concerned. it complicates configs a big. each needs to handle the repo's infra in it's own ecosystem. I like as little as possible configurations/scripts in my repos.
- from my perceptive, entire `scripts` folder is infra overhead which I'm trying (and sometimes fail) to avoid in my projects...
- file names should be lowercase, kebab-style. this alleviates some possible issues on case insensitive OSs.

thanks for the link. always good to see/learn new stuff, even though I have limited amount which I allocate to infrastructure...
