### ISSUE TITLE
any solution for the code lint ?

### ISSUE THREAD

**Issue by ZWkang** [wixplosives/sample-monorepo#64]
for example eslint, stylelint.
when our monorepo packages had their own lint check.
it is very hard to use one config for every packages.
and something like husky,lint-stage. it is hard to figure out where they should be.

**Comment by AviVahl** [comment]
This repository contains `eslint` already configured with `@typescript-eslint` and bunch of other plugins (`prettier`, `react`, etc).

You can add `.eslintrc` to specific folders to affect which rules are disable/enabled there, but I personally believe a repository should have a single, consistent root lint config.

Might be worth noting that `typescript` itself replaces some rules that were usually covered by eslint (in `.js` flows). e.g. rules checking for global variable access are now covered by type checking.

I personally don't like git pre-commit hooks, so `husky` or `lint-staged` will not be added here.
